/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.swapi.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param episodeId Id of the episode
 * @param releaseDate Release date of the film, format \"yyyy-MM-dd\"
 * @param producer Names of the producers
 */
@Serializable

data class Film (

    /* Id of the episode */
    @SerialName(value = "episode_id")
    val episodeId: kotlin.Int? = null,

    /* Release date of the film, format \"yyyy-MM-dd\" */
    @SerialName(value = "release_date")
    val releaseDate: kotlin.String? = null,

    /* Names of the producers */
    @SerialName(value = "producer")
    val producer: kotlin.String? = null

)

