/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.swapi.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param count Number of items in the response.
 * @param next Link to the next page of items.
 * @param previous Link to the previous page of items.
 */
@Serializable

data class Pagination (

    /* Number of items in the response. */
    @SerialName(value = "count")
    val count: kotlin.Int? = null,

    /* Link to the next page of items. */
    @SerialName(value = "next")
    val next: kotlin.String? = null,

    /* Link to the previous page of items. */
    @SerialName(value = "previous")
    val previous: kotlin.String? = null

)

