/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.swapi.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param climate Description of the climate.
 * @param name Display name of planet.
 */
@Serializable

data class Planet (

    /* Description of the climate. */
    @SerialName(value = "climate")
    val climate: kotlin.String? = null,

    /* Display name of planet. */
    @SerialName(value = "name")
    val name: kotlin.String? = null

)

