/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param birthYear Birthyear of person.
 * @param gender Gender of person.
 * @param name Display name of person.
 * @param homeWorld Indetifier of the planet the person is from.
 */
@Serializable

data class Person (

    /* Birthyear of person. */
    @SerialName(value = "birth_year")
    val birthYear: kotlin.String? = null,

    /* Gender of person. */
    @SerialName(value = "gender")
    val gender: kotlin.String? = null,

    /* Display name of person. */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* Indetifier of the planet the person is from. */
    @SerialName(value = "homeWorld")
    val homeWorld: kotlin.String? = null

)

