/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Unique identifier representing a specific planet.
 * @param name Display name of planet.
 */
@Serializable

data class Planet (

    /* Unique identifier representing a specific planet. */
    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    /* Display name of planet. */
    @SerialName(value = "name")
    val name: kotlin.String? = null

)

